-- 코드를 작성해주세요
SELECT HE.DEPT_ID, HD.DEPT_NAME_EN, HE.AVG_SAL
FROM (SELECT ANY_VALUE(DEPT_ID) DEPT_ID, ROUND(AVG(SAL)) AVG_SAL
        FROM HR_EMPLOYEES
        GROUP BY DEPT_ID) HE
        NATURAL JOIN
        HR_DEPARTMENT HD
        WHERE HD.DEPT_ID=HE.DEPT_ID
ORDER BY AVG_SAL DESC;


# SELECT DEPT_ID, DEPT_NAME_EN, AVG(SAL) AVG_SAL
# FROM
#     (SELECT *
#     FROM HR_DEPARTMENT HD
#         NATURAL JOIN
#         HR_EMPLOYEES HE
#         WHERE HD.DEPT_ID=HE.DEPT_ID) TEMP
# GROUP BY SAL

# SELECT *
# FROM
#     (SELECT *
#     FROM HR_DEPARTMENT HD
#         NATURAL JOIN
#         HR_EMPLOYEES HE
#         WHERE HD.DEPT_ID=HE.DEPT_ID) TEMP